title: Jae kwon's blog
author: GitHub User
email: ljk1256@naver.com
description:
baseurl:
url: 
twitter_username: 
github_username: "ljk1256"
instagram_username: "ljk1256" 
social:
  name: Lee Jae Kwon
  links:
    - https://github.com/ljk1256

disqus:
  shortname: jae kwon

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
